name: Deploy static content to Pages

on:
  push:
    branches:
      - "main"
      - "staging"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Prepare content for staging
        if: github.ref == 'refs/heads/staging'
        run: |
          mkdir -p public/staging
          mv !(public) public/staging

      - name: Prepare content for main
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p public
          mv !(public) public

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
